import { amazonPasteMayBeIncomplete, summarizeAmazonMatches } from '../shared/amazon'
import { coverageGap } from '../shared/engine'
import { FICTIONAL_AMAZON, FICTIONAL_BMO, FICTIONAL_PERIOD, FICTIONAL_TD } from './testing/fictionalFixtures'
import type { PrivateWorkspace } from './usePrivateWorkspace'

export default function ImportScreen({ workspace, onContinue }: { workspace: PrivateWorkspace; onContinue: () => void }) {
  const amazonSummary = summarizeAmazonMatches(workspace.amazonMatches)
  const gap = workspace.ranges.length ? coverageGap(workspace.ranges, workspace.period) : null
  const cards = Array.from(new Set(workspace.knownCards.concat(workspace.card))).filter(Boolean)
  return <section className="screen screen-frame import-page" aria-labelledby="import-title">
    <header className="page-heading"><div><p className="eyebrow">{workspace.period} · Import</p><h1 id="import-title" className="page-title">Import a statement</h1><p className="page-subtitle">Paste statement text from your bank. Everything is processed privately in this browser.</p></div><span className="privacy-pill">Nothing leaves this browser</span></header>
    <div className="import-grid"><main className="import-main">
      <div className="panel selector-card"><div className="row-three"><label className="field"><span>Reconciliation month</span><input aria-label="Import month" type="month" value={workspace.period} onChange={(event) => workspace.setPeriod(event.target.value)} /></label><label className="field"><span>Supported bank</span><select aria-label="Supported bank" value={workspace.bank} onChange={(event) => workspace.setBank(event.target.value as 'td' | 'bmo' | 'generic')}><option value="td">TD — 5 columns with balance</option><option value="bmo">BMO — signed amount</option><option value="generic">Other / generic paste</option></select></label><label className="field"><span>Card label</span><select aria-label="Card label" value={workspace.card} onChange={(event) => workspace.setCard(event.target.value)}>{cards.map(function (card) { return <option key={card}>{card}</option> })}</select></label></div></div>
      <form className="panel statement-card" onSubmit={(event) => { event.preventDefault(); workspace.parse() }}>
        <div className="card-heading"><div><h2>Paste statement text</h2><p>Select the transaction table on your bank page and paste it here. Keep the original columns intact.</p></div><span className="local-badge">Local processing</span></div>
        <textarea aria-label="Statement text" rows={9} spellCheck={false} value={workspace.text} onChange={(event) => workspace.setText(event.target.value)} />
        <div className="statement-footer"><p>Original pasted text is discarded after processing. Rows outside the month are reported, never silently dropped.</p><button className="btn primary" type="submit">Parse and add</button></div>
        <details className="utility-tools"><summary>Fictional samples</summary><div className="button-row"><button className="btn ghost" type="button" onClick={() => { workspace.setPeriod(FICTIONAL_PERIOD); workspace.setBank('td'); workspace.setCard('TD Visa'); workspace.setText(FICTIONAL_TD) }}>Load fictional TD sample</button><button className="btn ghost" type="button" onClick={() => { workspace.setPeriod(FICTIONAL_PERIOD); workspace.setBank('bmo'); workspace.setCard('BMO Mastercard'); workspace.setText(FICTIONAL_BMO) }}>Load fictional BMO sample</button></div></details>
        {workspace.parseError ? <p className="notice error" role="alert">{workspace.parseError}</p> : null}
        {workspace.summary ? <p className="notice good">Added {workspace.summary.added}; {workspace.summary.existingDupes} already present; {workspace.summary.pasteDupes} repeated in paste; {workspace.summary.postedUpgrades} posted upgrades; {workspace.summary.outOfPeriod} outside this month.</p> : null}
      </form>
      <details className="panel amazon-card"><summary><span><strong>Amazon order context <em>Optional</em></strong><small>Product context is private evidence only and never chooses a split.</small></span><span className="summary-chevron" aria-hidden="true">›</span></summary><div className="amazon-body"><label className="field"><span>Paste from Amazon Your Orders</span><textarea aria-label="Amazon order text" rows={6} value={workspace.amazonText} onChange={(event) => workspace.setAmazonText(event.target.value)} /></label><div className="button-row"><button className="btn" onClick={workspace.parseAmazon}>Read Amazon orders</button><button className="btn ghost" onClick={() => workspace.setAmazonText(FICTIONAL_AMAZON)}>Load fictional Amazon sample</button><button className="btn ghost" disabled={!workspace.amazonContext.orders.length} onClick={() => workspace.setAmazonContext({ orders: [], decisions: {}, advertisedOrderCount: null, duplicateBlocks: 0, invalidBlocks: 0 })}>Clear Amazon context</button></div>{workspace.amazonContext.orders.length ? <p className="notice good">Read {workspace.amazonContext.orders.length} fictional order(s). Compared with {amazonSummary.total} Amazon charge(s): {amazonSummary.exact} exact, {amazonSummary.ambiguous} ambiguous, {amazonSummary.unmatched} unmatched.{amazonPasteMayBeIncomplete(workspace.amazonContext) ? ' The copied pages may be incomplete.' : ''}</p> : null}</div></details>
    </main><aside className="import-rail"><section className="panel import-summary"><div className="summary-title"><h2>Import summary</h2><span>Local only</span></div><dl><div><dt>Rows loaded</dt><dd>{workspace.ledger.length}</dd></div><div><dt>Cards loaded</dt><dd>{new Set(workspace.ledger.map(function (row) { return row.card })).size}</dd></div><div><dt>Coverage</dt><dd>{workspace.ranges.length ? gap ? 'Gap remains' : 'Month covered' : 'Awaiting import'}</dd></div></dl><div className="summary-divider" /><button className="btn primary continue-full" onClick={onContinue} disabled={!workspace.ledger.length}>Continue to Review <span aria-hidden="true">›</span></button><p className="summary-note">Review accepted transactions before deciding ownership. Importing does not make the month ready.</p></section></aside></div>
  </section>
}
