import { buildMonthArchive, type MonthArchive } from '../shared/formats'
import { canClose, preCloseChecks } from '../shared/preClose'
import type { PeriodWorkflow } from '../shared/workflow'
import type { PrivateWorkspace } from './usePrivateWorkspace'
import { downloadJson } from './usePrivateWorkspace'

function money(value: number): string { return new Intl.NumberFormat('en-CA', { style: 'currency', currency: 'CAD' }).format(value) }
function monthName(period: string): string { return new Date(period + '-01T12:00:00').toLocaleDateString('en-CA', { month: 'long' }) }

export function archiveFor(workspace: PrivateWorkspace, workflow: PeriodWorkflow): MonthArchive | null {
  if (!workflow.mine || !workflow.partner) return null
  return buildMonthArchive({ toolVersion: '0.0.0-experiment', period: workspace.period, people: { a: workspace.names[workspace.meIndex] || 'Me', b: workspace.names[workspace.meIndex === 0 ? 1 : 0] || 'Partner' }, mine: workflow.mine.projection.items, theirs: workflow.partner.projection.items })
}

export default function SettleScreen(props: { workspace: PrivateWorkspace; workflow: PeriodWorkflow; busy: boolean; connected?: boolean; onClose: () => void; onFailNextClose?: () => void; onRecoverStale: () => void }) {
  const checks = preCloseChecks({ ledger: props.workspace.ledger, workflow: props.workflow, totalsConfirmed: props.workspace.confirmedTotals, currentProjection: props.workspace.projection() })
  const archive = archiveFor(props.workspace, props.workflow)
  const ready = !!archive && canClose(checks, props.workflow)
  const authoritative = props.workflow.archive
  const settlement = authoritative?.settlement || archive?.settlement
  const privateMine = props.workspace.names[props.workspace.meIndex] || 'You'
  const privatePartner = props.workspace.names[props.workspace.meIndex === 0 ? 1 : 0] || 'Partner'
  const mine = authoritative?.people.a || privateMine
  const partner = authoritative?.people.b || privatePartner
  const rows = authoritative ? authoritative.items.map(function (item) { return { date: item.date, merchant: item.merchant, amount: item.amount, share: item.shareOfPayer, payer: item.payer === 'a' ? mine : partner } }) : (props.workflow.mine?.projection.items || []).map(function (item) { return { ...item, payer: 'You' } }).concat((props.workflow.partner?.projection.items || []).map(function (item) { return { ...item, payer: 'Partner' } }))
  const result = settlement ? settlement.direction === 'square' ? mine + ' and ' + partner + ' are square' : settlement.direction === 'b_owes_a' ? partner + ' pays ' + mine + ' ' + money(settlement.net) : mine + ' pays ' + partner + ' ' + money(settlement.net) : 'Both current submissions are needed'
  return <section className="screen screen-frame settle-page" aria-labelledby="settle-title"><header className="page-heading"><div><p className="eyebrow">{props.workspace.period} · Settle</p><h1 id="settle-title" className="page-title">Settle {monthName(props.workspace.period)}</h1><p className="page-subtitle">Review both shared submissions, complete the checks, then close the month when everything agrees.</p></div><span className="fiction-pill">{props.connected ? 'Local API · fictional data only' : 'Fictional local simulation'}</span></header>
    <div className="settle-grid"><main className="settle-main"><section className={'settlement-hero ' + (props.workflow.status === 'closed' ? 'closed' : ready ? 'ready' : 'attention')}><div className="hero-heading"><div><p className="eyebrow">{props.workflow.status === 'closed' ? 'Month closed' : ready ? 'Ready to close' : 'Not ready to close'}</p><h2>{result}</h2><p>{props.workflow.status === 'retryable-error' ? props.workflow.errorMessage : props.workflow.status === 'stale' ? props.workflow.staleReason : 'This is the net result after offsetting the two privacy-filtered claims.'}</p></div><span className="hero-mark" aria-hidden="true">{props.workflow.status === 'closed' || ready ? '✓' : '!'}</span></div>{settlement ? <div className="hero-breakdown"><div><span>{partner} owes {mine}</span><strong>{money(settlement.aClaim)}</strong><small>{mine}-paid purchases</small></div><div><span>{mine} owes {partner}</span><strong className="theirs-value">{money(settlement.bClaim)}</strong><small>{partner}-paid purchases</small></div><div><span>Offset</span><strong className="offset-value">{money(settlement.net)}</strong><small>Net transfer</small></div></div> : null}{props.workflow.status === 'stale' ? <button className="btn ghost" onClick={props.onRecoverStale}>Refresh and review</button> : null}</section>
      <details className="panel submitted-sides"><summary><span><strong>Both submitted sides</strong><small>These are the privacy-filtered rows used for the result above.</small></span><span className="summary-chevron" aria-hidden="true">›</span></summary><div className="preview-body"><div className="table-scroll"><table><thead><tr><th>Date</th><th>Merchant</th><th>Paid by</th><th>Amount</th><th>Owed to payer</th></tr></thead><tbody>{rows.map(function (row) { return <tr key={row.payer + row.date + row.merchant}><td>{row.date}</td><td>{row.merchant}{'edited' in row && row.edited ? <span className="tag">edited</span> : null}</td><td>{row.payer}</td><td>{money(row.amount)}</td><td>{money(row.amount * (1 - row.share))}</td></tr> })}</tbody></table></div>{rows.some(function (row) { return ![0, .5, 1].includes(row.share) }) ? <p className="notice warn">Asymmetric shares are present. Confirm both people agreed before close.</p> : null}</div></details>
      <details className="panel settle-check-card" open><summary><span><strong>Settlement checks</strong><small>{ready ? 'Automatic checks and explicit acknowledgements are complete.' : 'Review every prerequisite before close.'}</small></span><span className="summary-chevron" aria-hidden="true">›</span></summary><div className="checks">{checks.map(function (check) { return <div className={check.passed ? 'check pass' : 'check warn'} key={check.id}><span>{check.passed ? '✓' : '!'}</span><div><strong>{check.label}</strong><small>{check.detail}</small></div></div> })}</div><p className="fine-print">Money is converted to integer cents. Exact half-cent claims round away from zero once per row, then the rounded claims are summed.</p><label className="ack"><input type="checkbox" checked={props.workspace.confirmedTotals} onChange={(event) => props.workspace.setConfirmedTotals(event.target.checked)} /> I checked the private count and net against my bank.</label></details>
    </main><aside className="settle-rail"><section className="panel close-card"><p className="eyebrow">{props.workspace.period}</p><h2>{props.workflow.status === 'closed' ? 'Month closed' : ready ? 'Ready to close' : 'Waiting for checks'}</h2>{props.workflow.status === 'closed' && props.workflow.archive ? <><p>Closed with {props.workflow.archive.items.length} shared item(s). The Worker-created archive is immutable.</p><button className="btn ghost continue-full" onClick={() => downloadJson('split-' + props.workspace.period + '-archive.json', props.workflow.archive)}>Download fresh archive</button></> : <><p>{props.connected ? 'The Worker validates both stored projections and creates the final archive. This does not send money.' : 'Closing finalizes this fictional record. It does not send money or confirm a bank transfer.'}</p><button className="btn primary continue-full" disabled={!ready || props.busy} onClick={props.onClose}>{props.workflow.status === 'retryable-error' ? 'Retry close safely' : props.busy ? 'Closing…' : 'Close month and archive'}</button>{props.onFailNextClose ? <button className="btn ghost continue-full" onClick={props.onFailNextClose} disabled={!ready}>Make next close fail (fictional)</button> : null}</>}</section><section className="panel agreement-card"><h2>Agreement</h2><p>If the results disagree, review the period, people, versions, and asymmetric shares before proceeding.</p></section></aside></div>
  </section>
}
