import type { PrivateWorkspace } from './usePrivateWorkspace'

export default function SetupScreen({ workspace, householdReady, connected = false }: { workspace: PrivateWorkspace; householdReady: boolean; connected?: boolean }) {
  return <section className="screen screen-frame setup-page" aria-labelledby="setup-title">
    <header className="page-heading"><div><p className="eyebrow">{workspace.period} · Setup</p><h1 id="setup-title" className="page-title">Set up this month</h1><p className="page-subtitle">Choose who is settling, which cards you use, and cautious defaults for unknown purchases.</p></div></header>
    <div className="setup-grid"><main className="settings-main">
      <section className="settings-section"><h2 className="section-title">Who and which cards</h2><p className="help">Fixed names and card labels prevent duplicate imports and make shared-file ownership unambiguous.</p>
        <div className="row-two"><label className="field"><span>First person</span><input value={workspace.names[0]} onChange={(event) => workspace.setNames([event.target.value, workspace.names[1]])} /></label><label className="field"><span>Second person</span><input value={workspace.names[1]} onChange={(event) => workspace.setNames([workspace.names[0], event.target.value])} /></label></div>
        <div className="row-two"><label className="field"><span>I am</span><select value={workspace.meIndex} onChange={(event) => workspace.setMeIndex(Number(event.target.value))}><option value={0}>{workspace.names[0]}</option><option value={1}>{workspace.names[1]}</option></select></label><label className="field"><span>Reconciliation month</span><input aria-label="Reconciliation month" type="month" value={workspace.period} onChange={(event) => workspace.setPeriod(event.target.value)} /></label></div>
        <label className="field"><span>Card labels, one per line</span><textarea rows={4} value={workspace.knownCards.join('\n')} onChange={(event) => workspace.setKnownCards(event.target.value.split(/\r?\n/).map(function (value) { return value.trim() }).filter(Boolean))} /></label>
      </section>
      <section className="settings-section"><h2 className="section-title">Auto-default small unknowns</h2><p className="help">Transactions below this amount with no matching rule are assigned automatically. Leave this at $0 for your first month so a hidden default cannot bias the result.</p><div className="row-two"><label className="field"><span>Threshold ($)</span><input aria-label="Auto-default threshold" type="number" min="0" step="1" value={workspace.threshold} onChange={(event) => workspace.setThreshold(Number(event.target.value))} /></label><label className="field"><span>Assign them to</span><select aria-label="Default unknown share" value={workspace.defaultUnknown} onChange={(event) => workspace.setDefaultUnknown(Number(event.target.value))}><option value={1}>All mine (conservative)</option><option value={0.5}>50/50</option></select></label></div></section>
    </main><aside className="setup-rail"><section className="panel household-card"><p className="eyebrow">Household access</p><h2>{householdReady ? 'Household selected' : 'Selection required'}</h2><p>If you created this household, invite your partner through Clerk. If you were invited, accept that invitation and select the existing household rather than creating another.</p><p className="fine-print">Clerk proves identity and membership. The Worker authorizes every shared workflow request from the verified household; private imports remain in this browser.</p><span className={'status-chip ' + (householdReady ? 'good' : 'warn')}>{householdReady ? connected ? 'Connected to local workflow API' : 'Ready for fictional simulation' : 'Choose a household above'}</span></section></aside></div>
  </section>
}
