import type { PeriodWorkflow, WorkflowStatus } from '../shared/workflow'
import type { PrivateWorkspace } from './usePrivateWorkspace'

const LABELS: Record<WorkflowStatus, string> = { draft: 'Draft', ready: 'Ready to submit', submitted: 'Submitted', replaced: 'Replaced', withdrawn: 'Withdrawn', 'partner-ready': 'Partner ready', stale: 'Stale — refresh required', closing: 'Closing', 'retryable-error': 'Retryable error', closed: 'Closed' }

export default function ShareStatusScreen(props: { workspace: PrivateWorkspace; workflow: PeriodWorkflow; displayStatus: WorkflowStatus; busy: boolean; connected?: boolean; onSubmit: () => void; onReplace: () => void; onWithdraw: () => void; onPartner?: () => void; onStale?: () => void; onRecover: () => void; onContinue: () => void }) {
  const projection = props.workspace.projection()
  const submitted = !!props.workflow.mine
  return <section className="screen screen-frame share-page" aria-labelledby="share-title"><header className="page-heading"><div><p className="eyebrow">{props.workspace.period} · Share / Status</p><h1 id="share-title" className="page-title">Share only what you decided</h1><p className="page-subtitle">Review the privacy-filtered projection, submit it, and see whether both household submissions are ready.</p></div><span className="fiction-pill">{props.connected ? 'Local API · fictional data only' : 'Fictional local simulation'}</span></header>
    <div className="share-grid"><main className="share-main"><section className="panel submission-card"><div className="submission-heading"><div><p className="eyebrow">Your submission</p><h2>{LABELS[props.displayStatus]}</h2></div><span>Version {props.workflow.version}</span></div>{props.workflow.staleReason ? <p className="notice warn">{props.workflow.staleReason}</p> : null}<div className="button-row">{!submitted || props.workflow.status === 'withdrawn' ? <button className="btn primary" disabled={props.busy || props.workspace.undecidedCount > 0 || !props.workspace.ledger.length} onClick={props.onSubmit}>Submit shared projection</button> : <><button className="btn primary" disabled={props.busy || props.workflow.status === 'closed' || props.workspace.undecidedCount > 0} onClick={props.onReplace}>Replace submission</button><button className="btn ghost" disabled={props.busy || props.workflow.status === 'closed'} onClick={props.onWithdraw}>Withdraw</button></>}{props.workflow.status === 'stale' ? <button className="btn ghost" onClick={props.onRecover}>Refresh and review</button> : null}</div>{props.workspace.undecidedCount ? <p className="fine-print">Submission and replacement are unavailable because {props.workspace.undecidedCount} posted purchase(s) still need a decision.</p> : null}</section>
      <details className="panel shared-preview" open><summary><span><strong>Exact shared-data preview</strong><small>Entirely private transactions and supporting evidence are absent.</small></span><span className="summary-chevron" aria-hidden="true">›</span></summary><div className="preview-body"><p className="privacy-callout">Only date, merchant, category, amount, payer share, and an optional edited flag cross the workflow gateway. Card labels, raw descriptions, rules, unfinished decisions, products, order IDs, and Amazon decisions stay private.</p><div className="table-scroll"><table><thead><tr><th>Date</th><th>Merchant</th><th>Amount</th><th>Payer share</th></tr></thead><tbody>{projection.items.map(function (item) { return <tr key={item.date + item.merchant}><td>{item.date}</td><td>{item.merchant}</td><td>${item.amount.toFixed(2)}</td><td>{Math.round(item.share * 100)}%</td></tr> })}</tbody></table></div>{!projection.items.length ? <p className="empty">No shared rows in the current projection.</p> : null}</div></details>
    </main><aside className="share-rail"><section className="panel partner-card"><p className="eyebrow">Partner status</p><h2>{props.workflow.partner ? 'Partner ready' : 'Waiting for partner'}</h2><p>{props.workflow.partner ? 'The other household submission is ready for settlement.' : props.connected ? 'Your partner must sign in to this same Clerk household and submit their projection.' : submitted ? 'Your fictional submission is ready for the partner simulation.' : 'Submit your shared projection first; the fictional partner response follows it.'}</p>{props.onPartner ? <button className="btn primary continue-full" onClick={props.onPartner} disabled={!submitted || !!props.workflow.partner || props.workflow.status === 'closed'}>Simulate fictional partner submission</button> : null}</section>{props.onStale ? <section className="panel simulation"><h2>Recovery demonstration</h2><p>Model a version changing while you review—the kind of response a real API may return.</p><button className="btn ghost continue-full" onClick={props.onStale} disabled={!props.workflow.mine || props.workflow.status === 'closed'}>Simulate partner change (stale)</button></section> : null}<button className="continue-btn" onClick={props.onContinue} disabled={!props.workflow.mine || !props.workflow.partner}>Continue to Settle <span aria-hidden="true">›</span></button></aside></div>
  </section>
}
